#!/bin/bash
echo "Exécution des tests PHPUnit avant commit..."
php ./bin/phpunit

if [ $? -ne 0 ]; then
    echo "Tests échoués. Annulation du commit."
    exit 1
fi

echo "Tous les tests ont réussi. Commit autorisé."
